# filepath: c:\Users\iphoe\OneDrive\Documents\GitHub\Property-Flipper-Game\game\ui\portfolio_view.py
# ...
def render(self, screen):
     # ... (clear buttons, title, cash, back button) ...
     # Property Listings
     # ...
     for prop in self.game_state.player.properties:
         # ...
         prop_val = prop.calculate_value(self.game_state.market, self.game_state) # <<< PASS game_state
         # ... (render text, status, buttons) ...
     # ...