#!/usr/bin/env node
/**
 * Assemble a press kit from assets this repo already generates.
 *
 * Screenshots, cover, banner and the social card already exist; a press kit
 * that is a second set of hand-crops is how they start disagreeing. This
 * copies the current cuts into `docs/press-kit/` and writes a fact sheet that
 * names the files, so regenerating is the same command as updating a store.
 *
 *     node scripts/press-kit.mjs
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'docs', 'press-kit');

const COPIES = [
  ['docs/marketing/cover-630x500.png', 'cover-630x500.png'],
  ['docs/marketing/banner-1920x620.png', 'banner-1920x620.png'],
  ['docs/marketing/social-1200x630.png', 'social-1200x630.png'],
  ['docs/marketing/steam-header-460x215.png', 'steam-header-460x215.png'],
  ['docs/marketing/steam-capsule-616x353.png', 'steam-capsule-616x353.png'],
  ['docs/marketing/steam-library-600x900.png', 'steam-library-600x900.png'],
  ['docs/marketing/steam-small-231x87.png', 'steam-small-231x87.png'],
  ['public/social-card.png', 'social-card.png'],
];

const SHOTS = [
  '01-menu.png',
  '02-market.png',
  '03-deal.png',
  '04-owned.png',
  '05-renovation.png',
  '06-board.png',
  '07-sale.png',
  '08-finance.png',
  '09-skills.png',
  '10-track-record.png',
];

mkdirSync(out, { recursive: true });
mkdirSync(path.join(out, 'shots'), { recursive: true });

const copied = [];
for (const [from, name] of COPIES) {
  const src = path.join(root, from);
  if (!existsSync(src)) {
    console.warn(`  skip ${name} — ${from} is missing (run npm run marketing)`);
    continue;
  }
  copyFileSync(src, path.join(out, name));
  copied.push(name);
}

for (const shot of SHOTS) {
  const src = path.join(root, 'docs', 'shots', shot);
  if (!existsSync(src)) {
    console.warn(`  skip shots/${shot} — run npm run shots`);
    continue;
  }
  copyFileSync(src, path.join(out, 'shots', shot));
  copied.push(`shots/${shot}`);
}

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const fact = `# Property Flipper — press kit

Version ${pkg.version}. Regenerated by \`npm run presskit\`; do not crop these by hand.

## The game

A real-estate flipping simulation that teaches how flip deals are actually underwritten. You buy distressed houses, estimate what they will be worth repaired, scope the work, and try to get out before commission, financing and carry eat the margin.

Play in a browser: https://ibuilder.github.io/Property-Flipper-Game/

## Fact sheet

| | |
| --- | --- |
| Title | Property Flipper |
| Genre | Simulation / education |
| Platforms | Windows, macOS, Linux, HTML5 |
| Price | Free (donations on itch.io) |
| Players | Single-player, offline |
| Engine | Custom TypeScript + Electron |
| License | MIT |
| Source | https://github.com/ibuilder/Property-Flipper-Game |

## Assets in this folder

${copied.map((f) => `- \`${f}\``).join('\n')}

Screenshots are 1280 × 800, the size the itch embed uses. Key art is a poster; screenshots are photographs of the running game.

Do not use the "Flip Empire" mockups. They depict a different game and teach the 70% rule wrong. See \`docs/marketing/README.md\`.
`;

writeFileSync(path.join(out, 'FACTSHEET.md'), fact);
console.log(`press-kit: ${copied.length} files in docs/press-kit/`);
